# Generated by Django 6.0 on 2025-12-11 09:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Department Name')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Device Name')),
                ('device_id', models.CharField(max_length=50, unique=True, verbose_name='Device ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial Number')),
                ('device_type', models.CharField(choices=[('monitor', 'Monitor'), ('infusion_pump', 'Infusion Pump'), ('ventilator', 'Ventilator'), ('defibrillator', 'Defibrillator'), ('ultrasound', 'Ultrasound'), ('xray', 'X-Ray'), ('other', 'Other')], max_length=50, verbose_name='Device Type')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=200, verbose_name='Model')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('warranty_expiry', models.DateField(verbose_name='Warranty Expiry')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='active', max_length=20, verbose_name='Status')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Last Maintenance')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Next Maintenance')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive Maintenance'), ('corrective', 'Corrective Maintenance'), ('emergency', 'Emergency Maintenance'), ('calibration', 'Calibration')], max_length=20, verbose_name='Maintenance Type')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Maintenance Date')),
                ('technician', models.CharField(max_length=200, verbose_name='Technician')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('description', models.TextField(verbose_name='Work Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('completed', models.BooleanField(default=True, verbose_name='Completed')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Next Maintenance Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='devices.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-date'],
            },
        ),
    ]