# Generated by Django 4.2.11 on 2026-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="assigned_technician",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Assigned Technician"
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="calibration_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="maintenance/calibration/",
                verbose_name="Calibration Certificate",
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="photo_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="maintenance/photos/",
                verbose_name="Photo Attachment",
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="sla_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="SLA Deadline"
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("waiting_parts", "Waiting Parts"),
                    ("completed", "Completed"),
                    ("verified", "Verified"),
                ],
                default="new",
                max_length=20,
                verbose_name="Work Order Status",
            ),
        ),
    ]
