# Generated by Django 4.2.11 on 2026-03-02 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PMTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive Maintenance"),
                            ("corrective", "Corrective Maintenance"),
                            ("emergency", "Emergency Maintenance"),
                            ("calibration", "Calibration"),
                        ],
                        default="preventive",
                        max_length=20,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("monitor", "Monitor"),
                            ("infusion_pump", "Infusion Pump"),
                            ("ventilator", "Ventilator"),
                            ("defibrillator", "Defibrillator"),
                            ("ultrasound", "Ultrasound"),
                            ("xray", "X-Ray"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("model", models.CharField(blank=True, max_length=200)),
                ("interval_days", models.PositiveIntegerField(default=90)),
                ("reminder_days_before", models.PositiveIntegerField(default=7)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["device_type", "manufacturer", "model", "name"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("reminder_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("due", "Due Now"),
                            ("overdue", "Overdue"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("soon", "Due Soon"),
                            ("urgent", "Urgent"),
                            ("overdue", "Overdue"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_tasks",
                        to="devices.device",
                    ),
                ),
                (
                    "source_maintenance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="devices.maintenance",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_tasks",
                        to="devices.pmtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "urgency"],
                "unique_together": {("device", "template", "due_date")},
            },
        ),
    ]
