# Generated by Django 4.2.11 on 2026-03-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_merge_20260302_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Started At"
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="stopped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Stopped At"
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="technician_signature",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Technician Signature"
            ),
        ),
        migrations.CreateModel(
            name="TechnicianNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("is_offline_created", models.BooleanField(default=False)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "maintenance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_notes",
                        to="devices.maintenance",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
